test:
	@./go.test.sh
.PHONY: test

coverage:
	@./go.coverage.sh
.PHONY: coverage

test-fast:
	go test ./...

tidy:
	go mod tidy

migrate:
	atlas --config file://prod.atlas.hcl --env prod migrate apply

generate:
	go generate ./...

lint-openapi:
	go tool vacuum lint -d _oas/openapi.yaml

lint-otel-registry:
	weaver registry check -r _otel

generate-otel-docs:
	weaver registry generate -t _otel_templates/ -r _otel markdown _docs

generate-otel-go:
	weaver registry generate -t _otel_templates/ -r _otel go internal/o11y

generate-otel-bundle:
	echo "# Generated by 'make generate-otel-bundle'" > .otel.registry.yml
	echo "# Do not edit this file directly" >> .otel.registry.yml
	echo "" >> .otel.registry.yml
	weaver registry resolve -r _otel >> .otel.registry.yml

generate-otel: generate-otel-docs generate-otel-go generate-otel-bundle
