openapi: 3.1.0
info:
  title: vega api
  description: vega api
  version: 1.0.0
servers:
  - url: 'http://vega.localhost'
tags:
  - name: observability
    description: Observability endpoints
paths:
  /health:
    get:
      operationId: "getHealth"
      description: "get health"
      tags: [observability]
      responses:
        '200':
          description: Health
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Health"
        default:
          $ref:  "#/components/responses/Error"
components:
  schemas:
    # Error-related schemas.
    TraceID:
      type: string
      description: W3C trace-id
      pattern: "[[:xdigit:]]{32}"
      example: 0af7651916cd43dd8448eb211c80319c
      externalDocs:
        url: "https://www.w3.org/TR/trace-context/#trace-id"
        description: "W3C Trace Context specification: Trace ID"
    SpanID:
      type: string
      description: W3C parent-id (span)
      pattern: "[[:xdigit:]]{16}"
      example: b7ad6b7169203331
      externalDocs:
        url: "https://www.w3.org/TR/trace-context/#parent-id"
        description: "W3C Trace Context specification: Parent ID"
    Error:
      title: Structured error
      description: Error occurred while processing request
      externalDocs:
        url: "https://vega.pages.gitlab.corp.mail.ru/docs/dev/spec/v2/errors"
        description: "Structured error specification"
      type: object
      required:
        - errorMessage
      properties:
        errorMessage:
          type: string
          description: "Human-readable error message"
          example: "Something went wrong"
        traceID:
          $ref: "#/components/schemas/TraceID"
        spanID:
          $ref: "#/components/schemas/SpanID"

    # Health-related schemas.
    Health:
      type: object
      description: Health status
      required:
        - status
        - version
        - commit
        - buildDate
      properties:
        status:
          type: string
          description: "Health status string"
          example: "ok"
        version:
          type: string
          description: "Service version"
          example: "1.0.0"
        commit:
          type: string
          description: "Service commit"
          example: "c1b2d3f4"
        buildDate:
          type: string
          description: "Service build date"
          example: "2022-01-01T00:00:00Z"
          format: date-time

  responses:
    Error:
      description: Structured error response.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

