// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateTaskOperation OperationName = "CreateTask"
	DeleteTaskOperation OperationName = "DeleteTask"
	GetHealthOperation  OperationName = "GetHealth"
	ListTasksOperation  OperationName = "ListTasks"
)
