// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateTask implements createTask operation.
//
// Create a new task with the provided title.
//
// POST /tasks
func (UnimplementedHandler) CreateTask(ctx context.Context, req *CreateTaskRequest) (r *Task, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteTask implements deleteTask operation.
//
// Delete a task by its unique identifier.
//
// DELETE /tasks/{id}
func (UnimplementedHandler) DeleteTask(ctx context.Context, params DeleteTaskParams) (r DeleteTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GenerateError implements generateError operation.
//
// Utility endpoint for testing error handling - always returns an error response.
//
// POST /tasks/error
func (UnimplementedHandler) GenerateError(ctx context.Context) (r *Error, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealth implements getHealth operation.
//
// Get health.
//
// GET /health
func (UnimplementedHandler) GetHealth(ctx context.Context) (r *Health, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTasks implements listTasks operation.
//
// Retrieve a list of all tasks in the system.
//
// GET /tasks
func (UnimplementedHandler) ListTasks(ctx context.Context) (r *TaskList, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
