name: Lint
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  # Check if there are any dirty changes after go mod tidy
  check-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: false

      - name: Get Go environment
        id: go-env
        run: |
          echo "cache=$(go env GOCACHE)" >> $GITHUB_ENV
          echo "modcache=$(go env GOMODCACHE)" >> $GITHUB_ENV

      # Notice: we're using read-only cache.
      #
      # See https://github.com/actions/setup-go/issues/357#issuecomment-1486486358
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ env.cache }}
            ${{ env.modcache }}
          key: ${{ runner.os }}-${{ runner.arch }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-go-

      - name: Run `go mod tidy`
        run: make tidy_all

      - name: Check git diff
        id: git-diff
        run: git diff --exit-code

  # Check if there are any dirty changes after go generate
  check-generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: false

      - name: Get Go environment
        id: go-env
        run: |
          echo "cache=$(go env GOCACHE)" >> $GITHUB_ENV
          echo "modcache=$(go env GOMODCACHE)" >> $GITHUB_ENV

      # Notice: we're using read-only cache.
      #
      # See https://github.com/actions/setup-go/issues/357#issuecomment-1486486358
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ env.cache }}
            ${{ env.modcache }}
          key: ${{ runner.os }}-${{ runner.arch }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-go-

      - name: Download dependencies
        run: go mod download && go mod tidy

      - name: Generate files
        run: make generate

      - name: Check git diff
        run: git diff --exit-code

  openapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: false

      - name: Get Go environment
        id: go-env
        run: |
          echo "cache=$(go env GOCACHE)" >> $GITHUB_ENV
          echo "modcache=$(go env GOMODCACHE)" >> $GITHUB_ENV

      # Notice: we're using read-only cache.
      #
      # See https://github.com/actions/setup-go/issues/357#issuecomment-1486486358
      #
      # TODO: consider caching vacuum installation?
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ env.cache }}
            ${{ env.modcache }}
          key: ${{ runner.os }}-${{ runner.arch }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-go-

      - name: Download dependencies
        run: go mod download && go mod tidy

      - name: Check the OpenAPI spec
        run: make lint-openapi
